Min journal post page
Firm-Collective/ai-journal pull request #69
Opened 2024-07-21 16:29 UTC by MinieMoe

## Describe your changes
- Implemented front end for home page where journal entries are posted:
  - Add bold fonts for post title
  - Made Post card component
  - Made Tag component
  - Used `Flatlist` as scroll page and implemented pull-to-refresh 
- Connected to Supabase to fetch posts:
  - Custom hook `useFetchJournalEntries` to fetch all posts, refresh for new posts, and whether still loading
  - Interfaces for Post data: `IJournalPost` and `IDBJournalPost`
 
## Issue ticket number and link
#54 

## Screenshots / Video
Add your media here...

## Checklist
- [X] I have performed a self-review of my code
- [X] I have used `npx expo-doctor` to review any dependency issues.
- [X] I have pulled and merged any recent changes from the main branch (no merge conflicts)
- [X] I have tested thoroughly any edge cases that might break the application
- [X] I have deleted any console.log statements and useless comments

2024-07-21 18:39 UTC, dave-cao requested changes
Nice work! 

Functionality questions
When we create a new text entry, and then go back to home, the new post won't show up until we refresh the page. Can we make it so it automatically shows up without needing to refresh?

Some styling changes / suggestions
- decrease the distance between posts a bit to fit the figma file
- add more shadow to bottom of post 

Figma:
![image](https://github.com/user-attachments/assets/ac16fb58-7052-4d35-9383-a8fdfc0b7f9e)

Branch
![image](https://github.com/user-attachments/assets/3b68a299-863a-4ae5-a5bc-c3386bc3b19a)

2024-07-21 18:44 UTC, dave-cao commented on components/user/home-screen/Post.tsx
> +  date: string; //TODO: or date object?
It's best practice to convert to date object, especially if we are going to use this more in the future.

2024-07-21 18:45 UTC, dave-cao requested changes
A few changes need to be made but great work so far!

2024-07-22 06:39 UTC, MinieMoe commented
@dave-cao I updated the code based on your request

There are few things I to suggest in the next meeting:
- Update the name of `MonoText` in `StyledText.tsx` since it used "Poppins", not "Space Mono"
- Use interface `IJournalEntry` to enforce type whenever we need to use `JournalEntry` component or anything related to it (ex: create, fetch journal entry)

Other styling problem in the home page:
- There's a gap on top and bottom of the scrolling portion, I dont know what caused it or how to fix it

2024-07-22 23:12 UTC, MinieMoe commented
@dave-cao I updated the code based on your request:
- reduce the spacing between each entry in the homepage
- add more shadow
- auto refresh for new entry on home page after submitting from text entry screen

There are few things I to suggest in the next meeting:
- Update the name of `MonoText` in `StyledText.tsx` since it used "Poppins", not "Space Mono"
- Use interface `IJournalEntry` to enforce type whenever we need to use `JournalEntry` component or anything related to it (ex: create, fetch journal entry)

Other styling problem in the home page:
- There's a gap on top and bottom of the scrolling portion, I dont know what caused it or how to fix it

2024-07-24 22:35 UTC, dave-cao approved these changes
Nice work!

2024-07-24 22:36 UTC, merged